export const PICTURES = [
  {
    id: 1,
    country: "UK",
    path: "/pics/picture01.jpeg",
    description:
      "Me having my lunch at a restaurant in eastbourne, I don't remember the name of the restaurant.",
    camera: "iPhone XR",
    size: "5.09MB",
  },
  {
    id: 2,
    country: "UK",
    path: "/pics/picture02.jpeg",
    description: "Going on a walk on eastbourne beach with family and friends.",
    camera: "iPhone XR",
    size: "8.88MB",
  },
  {
    id: 3,
    country: "UK",
    path: "/pics/picture03.jpeg",
    description:
      "A random orange cat that kept following me everywhere I went.",
    camera: "iPhone XR",
    size: "5.20MB",
  },
  {
    id: 4,
    country: "UK",
    path: "/pics/picture04.jpeg",
    description: "The seaside.",
    camera: "iPhone XR",
    size: "8.53MB",
  },
  {
    id: 5,
    country: "UK",
    path: "/pics/picture05.jpeg",
    description: "On top of the O2 Arena.",
    camera: "iPhone XR",
    size: "5.17MB",
  },
  {
    id: 6,
    country: "UK",
    path: "/pics/picture06.jpeg",
    description: "My keyboard.",
    camera: "iPhone XR",
    size: "6.25MB",
  },
  {
    id: 7,
    country: "UK",
    path: "/pics/picture07.jpeg",
    description: "",
    camera: "iPhone XR",
    size: "6.05MB",
  },
  {
    id: 8,
    country: "UK",
    path: "/pics/picture08.jpeg",
    description: "Code.",
    camera: "iPhone XR",
    size: "4.37MB",
  },
  {
    id: 9,
    country: "UK",
    path: "/pics/picture09.jpeg",
    description: "",
    camera: "iPhone XR",
    size: "7.00MB",
  },
  {
    id: 10,
    country: "UK",
    path: "/pics/picture10.jpeg",
    description: "My Prisma & Next.js stickers.",
    camera: "iPhone XR",
    size: "5.24MB",
  },
  {
    id: 11,
    country: "Kenya",
    path: "/pics/picture11.jpg",
    description: "Bunny.",
    camera: "iPhone 15",
    size: "6MB",
  },
  {
    id: 12,
    country: "Kenya",
    path: "/pics/picture12.jpg",
    description: "Giraffes in the savanna.",
    camera: "iPhone 15",
    size: "4.7MB",
  },
  {
    id: 13,
    country: "Kenya",
    path: "/pics/picture13.jpg",
    description: "Kenyan food.",
    camera: "iPhone 15",
    size: "7.4MB",
  },
  {
    id: 14,
    country: "Kenya",
    path: "/pics/picture14.jpg",
    description: "Holiday Inn hotel in Kenya.",
    camera: "iPhone 15",
    size: "8.7MB",
  },
  {
    id: 15,
    country: "Kenya",
    path: "/pics/picture15.jpg",
    description: "Kenyan resort.",
    camera: "iPhone 15",
    size: "12.5MB",
  },
  {
    id: 16,
    country: "Kenya",
    path: "/pics/picture16.jpg",
    description: "Jomo Kenyatta International Airport",
    camera: "iPhone 15",
    size: "6.6MB",
  },
  {
    id: 17,
    country: "UK",
    path: "/pics/picture17.jpg",
    description: "British Chips.",
    camera: "iPhone 15",
    size: "7.3MB",
  },
  {
    id: 18,
    country: "UK",
    path: "/pics/picture18.jpg",
    description: "A single wotsit near my keyboard.",
    camera: "iPhone 15",
    size: "8.2MB",
  },
];
